### ISSUE TITLE
Not able to get the grafana graph (9701)  running getting error 

### ISSUE THREAD

**Issue by vaibhavjayas** [openstack-exporter/openstack-exporter#10]
i am seeing the following error

Panel data error: TypeError: Cannot read property 'result' of undefined

**Comment by niedbalski** [comment]
Helo @vaibhavjayas,

I would like to understand your problem with more details, are you seeing this error
with any specific dashboard? can you point me which one are you trying  to use? Is
the exporter enabled?

Please provide me more details in order to being able to help you.

I will close this issue as I don't think it is directly related to the exporter. Feel free to re-open it
if you think is a bug.

Thanks
