### ISSUE TITLE
Cinder cannot get new token from keystone (401 source=cinder.go:101)

### ISSUE THREAD

**Issue by cognoz** [openstack-exporter/openstack-exporter#18]
**Openstack-exporter version:** v0.2.1 (openstack-exporter-0.2.1.linux-amd64.tar.gz
)
**Openstack version:** queens 17.1.12

**Issue:** After starting, cinder-exporter successfully exports metrics for a time equal token expiration time in keystone. After that, we are receiving this error:
`invalid status (401): {\"error\": {\"message\": \"The request you have made requires authentication.\", \"code\": 401, \"title\": \"Unauthorized\"}}" source="cinder.go:101"`

Restarting openstack-exporter solves problem until token revocation.

**Comment by niedbalski** [comment]
Hello @cognoz 

Could you please test the latest image from master and see if the problem is still reproducible? [0]
The PR [1] should have fixed it, so please let me know if the problem is gone in order to produce a stable build.

Thank you in advance.
[0] docker pull quay.io/niedbalski/openstack-exporter-linux-amd64:master
[1] https://github.com/openstack-exporter/openstack-exporter/pull/19

**Comment by Alexvianet** [comment]
Have the same issue I receive cinder metrics for 1h and then they have gone:
![Screenshot from 2019-09-05 14-38-23](https://user-images.githubusercontent.com/17483589/64338654-fc145a80-cfea-11e9-8087-b4c3de6baeb1.png)

**Comment by niedbalski** [comment]
@Alexvianet can you please check with the current master image?

**Comment by Alexvianet** [comment]
i got 
```
ERRO[6334] invalid status (401): {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}  source="cinder.go:137"
```
in hour

**Comment by niedbalski** [comment]
@Alexvianet Could you please retry docker run -v "/tmp/clouds.yml":/etc/openstack/clouds.yml -it quay.io/niedbalski/openstack-exporter-linux-amd64:master default ?

Thank you!

**Comment by Alexvianet** [comment]
ERRO[5891] invalid status (401): {"error": {"message": "The request you have made requires authentication.", "code": 401, "title": "Unauthorized"}}  source="cinder.go:139"
The same

**Comment by niedbalski** [comment]
@Alexvianet @cognoz 

Apologies guys, I had forgotten to update the dependencies from goose.v3, I've verified myself that the token gets regenerated, so If you could please test 

docker pull quay.io/niedbalski/openstack-exporter-linux-amd64:master

To check if the problem is gone, I'd be grateful.

Thanks!

**Comment by cognoz** [comment]
Hi, thx! I deployed it right now.
I'll check it later (12hrs token) and write here.

**Comment by cognoz** [comment]
Confirm, everything works so far.
Please, add new release with these fixes.

**Comment by Alexvianet** [comment]
Please, add new release with these fixes

**Comment by niedbalski** [comment]
@Alexvianet @cognoz v0.3.0 include these fixes. Please test/upgrade to docker pull quay.io/niedbalski/openstack-exporter-linux-amd64:v0.3.0
