### ISSUE TITLE
Add project_name, flavor_name and tenant_name in metrics

### ISSUE THREAD

**Issue by fabius987** [openstack-exporter/openstack-exporter#58]
Hi,
can I ask you to add project-name and tenant-name to the metrics, to help the identification of both?
I think that using project-id and tenant-id only is a limitation of the exporter in a very big environment.

What I expect is something like this :

openstack_neutron_network_ip_availabilities_used{cidr="192.168.168.0/24",network_id="9150eba3-79b2-443c-8889-fd17dd82b605",network_name="private",project_id="5909e7d5f0d1403398c055b498eb6b30",**project_name="first-project"**,subnet_name="private"} 6

openstack_nova_server_status{address_ipv4="",address_ipv6="",availability_zone="nova",flavor_id="4492a7a2-2899-4a31-b82b-19bfc319bec1",**flavor_name="first-flavor"**,host_id="184b2ca0f192e5e2fd734a27cdbac3329730614d2917e51148780e0e",id="c078cfb3-73db-472c-b203-501ce0839f4a",name="FW-FORTIGATE",status="ACTIVE",tenant_id="de12a24cc96c4485a4024674ce02d32f",**tenant_name="first-tenant",project_id="",project_name=""**,user_id="a450fbdf170d4ba49effe18bd09089e5",uuid="c078cfb3-73db-472c-b203-501ce0839f4a"} 0

openstack_cinder_volume_status{bootable="true",id="cc2ab79e-a10b-4d0d-a91f-a6ca0dc45468",name="VM_SSD",size="50",status="in-use",tenant_id="9a3b98a2b0934f2f8ebf055c71d55485",**tenant_name="first-tenant",project_id="",project_name=""**,volume_type="SSD"} 5

Thanks in advance,

Fabio Pasetti

**Comment by alistarle** [comment]
I asked myself the same question when adding new metrics but we really need to understand the impact in term of storage in prometheus, and performance for the exporter to generate the metrics :
- The first point is maybe the simplest, because 1 project_id = 1 project_name so it does not increase the cardinality of the label and the metric number, just the size of the sample itself.
- The second point is a little bit more complicated, as we don't always know the flavor_name or project_name, because the API call to gather the data often return only the ID of the related object. This imply maybe to store somewhere in cache/global variable the relation project_id/project_name and use it when needed in all metrics ?

**Comment by mnaser** [comment]
FWIW, I think it would be better if we actually have a metric with the existance of tenants/flavors and their info, then you could use Prometheus queries to match things up together.

I _think_ that's possible?

**Comment by niedbalski** [comment]
> FWIW, I think it would be better if we actually have a metric with the existance of tenants/flavors and their info, then you could use Prometheus queries to match things up together.
> 
> I _think_ that's possible?

Can you expand on this proposal?

**Comment by mnaser** [comment]
My query writing skillset isn't as strong but we have keystone projects/users (with names) and we have IDs in other entities

https://docs.ceph.com/docs/master/mgr/prometheus/#correlating-drive-statistics-with-node-exporter

Someone could do something similar to what is suggested here

**Comment by alistarle** [comment]
Thanks for the ceph documentation, I am not fluent in promql too so exemple are welcome ! I will try that in the future days and if it is working I think we can close this issue and instead git some example, maybe in the grafana_dashboard repository

**Comment by niedbalski** [comment]
@alistarle I would be very grateful if you can expand the grafana dashboard with these examples. For the time being, I am closing this issue.
